### PR TITLE
fix: adjusted padding; fixed warning.

### PR DESCRIPTION
**Pull request by Tulun**
Adjusted padding slightly. Can you lmk if this is ok @Tommy1231232 ?
Signed-off-by: Tulun <jaykiraly@gmail.com>

### CODE REVIEW

**Review by daywiss — COMMENTED** [review]
i dont see any code to fix padding, looks like it was linted or something

**Review by Tommy1231232 — CHANGES_REQUESTED** [review]
@Tulun what happened to the word "Across" in the logo in the top right? 
Screen Shot 2022-03-28 at 7 59 00 AM

**Comment by Tulun** [comment]
> @Tulun what happened to the word "Across" in the logo in the top right? Screen Shot 2022-03-28 at 7 59 00 AM

My code did not change this. This was already existing. 

It seems like at a certain breakpoint, the logo changes. 

My screen:

Screen Shot 2022-03-28 at 7 37 48 AM


CSS:
Screen Shot 2022-03-28 at 7 36 51 AM

**Comment by Tommy1231232** [comment]
@Tulun feedback from Jesper:
Screen Shot 2022-03-28 at 11 30 33 AM

**Comment by Tulun** [comment]
> @Tulun in this PR when I expand the page on my external monitor I see this:
> 
> Screen Shot 2022-03-28 at 11 28 16 AM



Screen Shot 2022-03-28 at 8 34 29 AM

This is on my external monitor. I have no idea why that's happening.

**Comment by Tulun** [comment]
> > @Tulun in this PR when I expand the page on my external monitor I see this:
> > Screen Shot 2022-03-28 at 11 28 16 AM
> 
> Screen Shot 2022-03-28 at 8 34 29 AM
> 
> This is on my external monitor. I have no idea why that's happening.

Got it. Should be fixed. @Tommy1231232 

Jesper confirmed the padding is now fixed.

**Comment by Tommy1231232** [comment]
It doesn't happen in master which i

> 

It doesn't happen in master. Just this PR so we should fix before merging. Try slowly expanding your screen. You'll notice it does it only at a certain point. Will attach a video: 



> > @Tulun in this PR when I expand the page on my external monitor I see this:
> > Screen Shot 2022-03-28 at 11 28 16 AM
> 
> Screen Shot 2022-03-28 at 8 34 29 AM
> 
> This is on my external monitor. I have no idea why that's happening.

Trying to send a video/reproduce but it's not happening now so will ignore for now.

**Review by Tommy1231232 — APPROVED** [review]

**Pull request merged**
