### PR TITLE
ENH: Add DAI

### PR DESCRIPTION
**Pull request by cc7768**
Adds DAI to the `TOKENS_LIST` mapping and adds the dai logo.

Signed-off-by: Chase Coleman <cc7768@gmail.com>

### CODE REVIEW

**Comment by cc7768** [comment]
I used the frontend to go from L1->L2 (via the canonical bridge):

* Arbitrum went through smoothly
* Boba went through smoothly
* Optimism doesn't seem to have gone through?

L2->L1 seems to have gone smoothly on all accounts. Relayer instantly sped up the transactions and the relays all successfully settled.

**Comment by Gamaranto** [comment]
Do we need to add the rate model for DAI in the sdk? @daywiss

**Review by Gamaranto — APPROVED** [review]
The code looks good to me. Let's double check on the rate models though

**Comment by cc7768** [comment]
We won't support DAI until v2.

**Comment by cc7768** [comment]
Reopening -- We are planning to support DAI on Arbitrum and Boba prior to v2.

**Comment by cc7768** [comment]
> Do we need to add the rate model for DAI in the sdk? @daywiss

I believe that we get this "for free" once we've added it to the `RateModelStore` (see, [lpFeeCalculator](https://github.com/UMAprotocol/protocol/blob/4adff3de6e24f6e60620d47321e95e8f07902964/packages/sdk/src/across/lpFeeCalculator.ts#L16-L43)). The [rate model has been added](https://etherscan.io/tx/0x02b1c7790e8277672df135738c452edb400ea76940d53f5f22a3f0e690578a63#eventlog) to the `RateModelStore`.

**Review by Tulun — APPROVED** [review]
Could be more efficient.

**Comment by daywiss** [comment]
yea rate models are on chain now @Gamaranto

**Review by daywiss — APPROVED** [review]
lgtm

**Comment by Tommy1231232** [comment]
@cc7768 @daywiss @Gamaranto we need to remove wallet connect before merging this.

**Comment by Tommy1231232** [comment]
With all of these assets not alphabetized it looks really sloppy. We should alphabetize these before launching this. I know this will take some time though...wdyt?  @daywiss @Gamaranto @cc7768

**Comment by cc7768** [comment]
Closed in favor of #184

**Pull request closed without merging**
